[workspace]
resolver = "2"

default-members = [
    "app",
]

members = [
    "app",
    "package",
    "xtask",
]

[workspace.package]
edition = "2021"
repository = "https://github.com/oxidecomputer/thundermuffin"

[workspace.dependencies]
anyhow = "1.0.101"
cargo_metadata = "0.18"
clap = { version = "4.5.59", features = ["derive"] }
indoc = "2"
socket2 = { version = "0.4.10", features = ["all"] }
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "macros", "time"] }
toml = "0.8"
